version: "3"

networks:
  web:
    external: true

services:
  landing-page:
    build: .
    labels:
      - traefik.http.routers.home.rule=Host(`ermo.space`)
      - traefik.http.routers.home.tls=true
      - traefik.http.routers.home.tls.certresolver=lets-encrypt
    networks:
      - web